###
### DO NOT MODIFY THIS FILE.  THIS FILE HAS BEEN AUTOGENERATED
###

FROM chromedp/headless-shell

COPY entry.sh /opt/bin/
ENTRYPOINT ["/opt/bin/entry.sh"]
CMD ["/bin/sh"] 

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/sh"]
